name: Publish to Pub.dev

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version to tag and publish'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # 3.6.0
        with:
          fetch-depth: 0
          # Bypass protected branch setting by using a service account PAT
          # see more at: https://github.com/community/community/discussions/13836
          token: ${{ secrets.PAT }}

      - name: Install Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 #2.19.0
        with:
          flutter-version: '3.24.3'

      - name: Create Git Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version based on tag
        run: |
          chmod +x ./.github/workflows/update_version.sh
          ./.github/workflows/update_version.sh
      
      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a #4.16.0
        id: commit
        with:
          commit_message: "chore: bumped versions to ${{ github.event.inputs.version }}"

      - name: Setup Pub Credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./.github/workflows/pub_login.sh

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

      - name: Publish Package
        run: flutter pub publish -f